const api_url="https://retoolapi.dev/AnbI2N/data";

initialise_data()

async function initialise_data() {
  // Our basis for checking whether our API url is newly generated is if it has an item with ID 1 (the dummy data generated by the tool)

  // Storing response
  const response = await fetch(api_url);

  // Storing data in form of JSON
  var data = await response.json();

  var has_dummy_data = data.some(function(item){ return item.id == 1});

  if(has_dummy_data) {
    for (var item of data_setup) {
      console.log(item)
      await fetch(api_url, {
        method: "POST",
        body: JSON.stringify(item),
        headers: {
          "Content-type": "application/json; charset=UTF-8"
        }
      })
      .then((response) => response.json())
      .then((json) => console.log(json));
    }

    // Remove the dummy data
    remove(1)
  }
}

// This file contains all global scripts that should work on ALL pages of the website
// This script needs to be added on every HTML page for all the pages to access these scripts

const loginButton = document.getElementsByClassName('login-link');
const logoutButton = document.getElementsByClassName('logout-link');

console.log("User logged in? " + sessionStorage.getItem('userStatus'))

// Check if the user is logged in. If they are, the Log in button will be replaced with Log out
if(sessionStorage.getItem('userStatus') == 'loggedIn') {
    console.log('User is logged in')
    loginButton[0].style.display = 'none';
    logoutButton[0].style.display = 'inline-block';
} else {
    console.log('User is logged out')
    loginButton[0].style.display = 'inline-block';
    logoutButton[0].style.display = 'none';
}


function logout() {
  let confirmAction = confirm("Are you sure you want to logout?");

  if(confirmAction) {
    console.log("Logging out..")
    console.log("Setting session to logged out...")
    sessionStorage.setItem('userStatus', 'loggedOut')
  } else {
    // Do nothing
  }
  
}